.\"
.\"
.\"
.\"
.\" $Id: hinagata.3,v 1.1.1.1 2001/03/28 03:07:35 kobayasi Exp $
.\"
.Dd Sep 1, 1999
.Dt PEPPMALLOC 3
.Os FreeBSD
.Sh 名前
.Nm 関数名
.Nd 関数の説明
.Sh 機能
.Fd #include <neuro.h>
.Ft Pe **
.Fn Peppmalloc "const int num"
.Sh 解説

.Fn 関数名

.Sh 返り値

.Sh 例

.Bd -literal -offset indent
#include "neuro.h"

.Sh 関連項目

.Sh 歴史
1994年に開発し，それ以降メンテナンスされています．関西大学総合情報学部に
おいて，1997年から知識情報処理実習IIで使用しています．
.Sh バグ
特にありません．発見した場合は，kobayasi@res.kutc.kansai-u.ac.jp まで
ご連絡下さい．
